### ISSUE TITLE
Terms of use

### ISSUE THREAD

**Issue by vimalthilak** [yizhangzzz/transformers-lego#1]
@yizhangzzz Thank you for providing an implementation for your Unveiling Transformers paper. Very nice work! 

Would it be possible for you to add a license in order for ensure your code can be used by the rest of the research and broader ML community?

Best!

**Comment by yizhangzzz** [comment]
Hi, @vimalthilak thanks a lot for the reminder!  I have added an Apache license to the repo. Have fun!
